Controllers/CreditCardController.cs
using KursovaWorkDAL.Entity.Entities;
using KursovaWork.Models;
using KursovaWorkBLL.Services.MainServices.CardService;
using Microsoft.AspNetCore.Mvc;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace KursovaWork.Controllers
{
    /// <summary>
    /// Контролер, що відповідає за операції пов'язані з методами оплати.
    /// </summary>
    public class CreditCardController : Controller
    {
        /// <summary>
        /// Інтерфейс сервісу для опрацювання запиту
        /// </summary>
        private readonly ICardService _cardService;

        /// <summary>
        /// Об'єкт класу ILogger для логування подій 
        /// </summary>
        private readonly ILogger<CreditCardController> _logger;

        /// <summary>
        /// Ініціалізує новий екземпляр класу <see cref="CreditCardController"/>.
        /// </summary>
        /// <param name="cardService">Інтерфейс сервісу для опрацювання запиту</param>
        /// <param name="logger">Об'єкт класу ILogger для логування подій </param>
        public CreditCardController(ICardService cardService, ILogger<CreditCardController> logger)
        {
            _cardService = cardService;
            _logger = logger;
        }

        /// <summary>
        /// Перехід на сторінку методів оплати.
        /// </summary>
        /// <returns>Сторінка методів оплати.</returns>
        public IActionResult CreditCard()
        {
            _logger.LogInformation("Перехід до методу переходу на сторінку методів оплати");

            _logger.LogInformation("Поля для додавання карти є виключені під час прогрузки");
            ViewBag.Input = false;

            if (_cardService.CardExists())
            {
                _logger.LogInformation("Метод оплати є підключеним у користувача");

                SetCreditCardInfo();
            }

            _logger.LogInformation("Перехід на сторінку методів оплати");
            return View("~/Views/CreditCard/CreditCard.cshtml");
        }

        /// <summary>
        /// Запис інформації кредитної карти у ViewBag
        /// </summary>
        public void SetCreditCardInfo()
        {
            Card user = _cardService.GetByLoggedInUser();
            string cardNumber = user.CardNumber;
            ViewBag.CardNumber = "···· ···· ···· " + cardNumber.Substring(cardNumber.Length - 4);
            ViewBag.CardHolderName = user.CardHolderName;
            ViewBag.Month = user.ExpirationMonth;
            ViewBag.Year = user.ExpirationYear;
            ViewBag.Card = true;

            _logger.LogInformation("Заполучення всіх даних про метод оплати користувача");
        }

        /// <summary>
        /// Обробка форми додавання методу оплати.
        /// </summary>
        /// <param name="model">Модель з даними методу оплати.</param>
        /// <returns>Перенаправлення на головну сторінку або повторний вивід форми з помилками.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreditCard(CreditCardViewModel model)
        {
            _logger.LogInformation("Вхід до методу видалення методу оплати");

            if (ModelState.IsValid)
            {
                _cardService.AddCard(model.ToCard());

                return Json(new { success = true }); 
            }

            _logger.LogInformation("Дані не пройшли верифікацію");
            
            var errors = new
            {
                CardHolderName = ModelState[nameof(CreditCardViewModel.CardHolderName)].Errors.FirstOrDefault()?.ErrorMessage ?? "",
                CardNumber = ModelState[nameof(CreditCardViewModel.CardNumber)].Errors.FirstOrDefault()?.ErrorMessage ?? "",
                ExpirationMonth = ModelState[nameof(CreditCardViewModel.ExpirationMonth)].Errors.FirstOrDefault()?.ErrorMessage ?? "",
                ExpirationYear = ModelState[nameof(CreditCardViewModel.ExpirationYear)].Errors.FirstOrDefault()?.ErrorMessage ?? "",
                CVV = ModelState[nameof(CreditCardViewModel.CVV)].Errors.FirstOrDefault()?.ErrorMessage ?? ""
            };

            _logger.LogInformation("Показуємо поля введення зразу ж після прогрузки");
            ViewBag.Input = true;
            return Json(new { success = false, errors });
        }

        /// <summary>
        /// Видалення методу оплати.
        /// </summary>
        /// <returns>Перенаправлення на сторінку методів оплати.</returns>
        public IActionResult DeleteCreditCard()
        {
            _logger.LogInformation("Вхід до методу видалення методу оплати");

            _cardService.DeleteCard();

            _logger.LogInformation("Поля для додавання карти є виключені під час прогрузки");
            ViewBag.Input = false;

            _logger.LogInformation("Перехід на сторінку методів оплати");
            return View("~/Views/CreditCard/CreditCard.cshtml");
        }
    }
}

Views/Shared/_Footer.cshtml
<footer class="footer">
    <div class="LinksContainer">
        <div class="d-xxl-flex flex-row justify-content-between gap-3">
            <div class="boxFooter__column boxFooter__column1">
                <div class="boxFooterColumn">
                    <div class="boxFooterColumn__headline">
                        <div class="webCustom boxFooterColumnHeadline">
                            <h5 class="boxFooterColumnHeadline__headline boxFooterColumnHeadline__d200">
                                <span class="boxFooterColumnHeadline__main">Volkswagen</span>
                            </h5>
                        </div>

                    </div>
                    <div class="boxFooterColumn__linkList">
                        <div class="boxFooterColumnLinkList d-xxl-flex flex-column justify-content-lg-between gap-2" data-width="100%">
                            <div class="list-item" style="">
                                <span class="boxFooterColumnLinkListLink">
                                    <a class="kwcBasicLinkTagIntern Disclaimer-text text-decoration-none" href="/brand-and-news/news" title="Актуальні новини світу Volkswagen">
                                        <span>Новини</span>
                                    </a>
                                </span>
                            </div>
                            <div class="list-item" style="">
                                <span class="boxFooterColumnLinkListLink">
                                    <a class="poiToolsKwcLinkTagExtern Disclaimer-text text-decoration-none" href="https://www.vw-commercial.com.ua" title="Комерційні автомобілі Volkswagen">
                                        <span>Volkswagen комерційні автомобілі</span>
                                    </a>
                                </span>
                            </div>
                            <div class="list-item" style="">
                                <span class="boxFooterColumnLinkListLink">
                                    <a class="poiToolsKwcLinkTagSvn Disclaimer-text text-decoration-none" href="https://stockcars.porscheinformatik.com/mainframe/api/redirect/result-list?country=UA&amp;brand=VW&amp;stockCar=true" data-poi-type="svn" data-poi-model="" data-kwc-popup="blank">
                                        <span>Склад авто в Україні</span>
                                    </a>
                                </span>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
            <div class="boxFooter__column boxFooter__column2">
                <div class="boxFooterColumn">
                    <div class="boxFooterColumn__headline">
                        <div class="webCustom boxFooterColumnHeadline">
                            <h5 class="boxFooterColumnHeadline__headline boxFooterColumnHeadline__d200">
                                <span class="boxFooterColumnHeadline__main">Сервіс</span>
                            </h5>
                        </div>

                    </div>
                    <div class="boxFooterColumn__linkList">
                        <div class="boxFooterColumnLinkList d-xxl-flex flex-column justify-content-lg-between gap-2" data-width="100%">
                            <div class="list-item" style="">
                                <span class="boxFooterColumnLinkListLink">
                                    <a class="kwcBasicLinkTagIntern Disclaimer-text text-decoration-none" href="/dealer-search" title="Пошук дилера Volkswagen">
                                        <span>Пошук дилера</span>
                                    </a>
                                </span>
                            </div>
                            <div class="list-item" style="">
                                <span class="boxFooterColumnLinkListLink">
                                    <a class="kwcBasicLinkTagIntern Disclaimer-text text-decoration-none" href="/contacts-dealer-only/vehichle-inquiry">
                                        <span>Відгуки та пропозиції</span>
                                    </a>
                                </span>
                            </div>
                            <div class="list-item" style="">
                                <span class="boxFooterColumnLinkListLink">
                                    <a class="kwcBasicLinkTagIntern Disclaimer-text text-decoration-none" href="/brand-and-news/news/newsletter" title="Підписка на новини Volkswagen ">
                                        <span>Підписка на новини</span>
                                    </a>
                                </span>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
            <div class="support d-xl-flex flex-column">
                <div class="boxFooterColumn">
                    <div class="boxFooterColumn__headline">
                        <div class="webCustom boxFooterColumnHeadline">
                            <h5 class="boxFooterColumnHeadline__headline boxFooterColumnHeadline__d200">
                                <span class="boxFooterColumnHeadline__main">Підтримка</span>
                            </h5>
                        </div>

                    </div>
                    <div class="boxFooterColumn__linkList">
                        <div class="boxFooterColumnLinkList list-unstyled d-xxl-flex flex-column justify-content-lg-between gap-2" data-width="100%">
                            <div class="list-item">
                                <span class="boxFooterColumnLinkListLink">
                                    <a class="kwcBasicLinkTagIntern Disclaimer-text text-decoration-none" href="/impressum-1/tov-porsche-ukraine" title="Volkswagen в Україні">
                                        <span>Volkswagen в Україні</span>
                                    </a>
                                </span>
                            </div>
                            <div class="list-item">
                                <span class="boxFooterColumnLinkListLink">
                                    <a class="kwcBasicLinkTagIntern Disclaimer-text text-decoration-none" href="/impressum-1/tov-porsche-ukraine" title="Конфіденційність персональних даних">
                                        <span>Конфіденційність персональних даних</span>
                                    </a>
                                </span>
                            </div>
                            <div class="listItem">
                                <span class="boxFooterColumnLinkListLink">
                                    <a class="poiToolsKwcLinkTagExtern Disclaimer-text text-decoration-none" href="https://www.porscheukraine.com.ua/uk/company/comliance/sistema-whistle-blower" data-kwc-popup="blank">
                                        <span>Система повідомлення про порушення (Whistleblower System)</span>
                                    </a>
                                </span>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
            <div class="socialLinks d-xl-flex flex-column">
                <div class="boxFooterColumn__headline">
                    <div class="webCustom boxFooterColumnHeadline">
                        <h5 class="boxFooterColumnHeadline__headline boxFooterColumnHeadline__d200">
                            <span class="boxFooterColumnHeadline__main">Соціальні мережі</span>
                        </h5>
                    </div>

                </div>
                <div class="boxFooterSocialLinks list-unstyled d-xxl-flex flex-column justify-content-lg-between gap-2">
                    <div class="list-item" style="">
                        <div class="d-xl-flex flex-xxl-row">
                            <div class="boxFooterSocialLinksChildImage">
                                <img src="//cf-cdn-v6.volkswagen.at/media/Box_Footer_SocialLinks_Child_Image_Component/root-uapkw-footer-socialLinks-65057-image/default/c4983ad5/1674458852/social-facebook.svg" alt="">
                            </div>
                            <span class="boxFooterSocialLinksChildLink">
                                <a class="LinkTagExtern text-decoration-none Disclaimer-text" href="https://www.facebook.com/VolkswagenUA/">
                                    <span>Facebook</span>
                                </a>
                            </span>
                            <div class="boxFooterSocialLinksChildAltText">
                            </div>
                        </div>
                    </div>
                    <div class="list-item" style="">
                        <div class="d-xl-flex flex-xxl-row">
                            <div class="boxFooterSocialLinksChildImage">
                                <img src="//cf-cdn-v6.volkswagen.at/media/Box_Footer_SocialLinks_Child_Image_Component/root-uapkw-footer-socialLinks-65058-image/default/f354ecf8/1674458852/social-youtube.svg" alt="">
                            </div>
                            <span class="boxFooterSocialLinksChildLink">
                                <a class="LinkTagExtern text-decoration-none Disclaimer-text" href="https://www.youtube.com/user/VolkswagenUA">
                                    <span>YouTube</span>
                                </a>
                            </span>
                            <div class="boxFooterSocialLinksChildAltText">
                            </div>
                        </div>
                    </div>
                    <div class="list-item" style="">
                        <div class="d-xl-flex flex-xxl-row">
                            <div class="boxFooterSocialLinksChildImage">
                                <img src="//cf-cdn-v6.volkswagen.at/media/Box_Footer_SocialLinks_Child_Image_Component/root-uapkw-footer-socialLinks-65059-image/default/916dc838/1677140935/social-instagram.svg" alt="">
                            </div>
                            <span class="boxFooterSocialLinksChildLink" role="button">
                                <a class="LinkTagExtern text-decoration-none Disclaimer-text" href="https://www.instagram.com/volkswagen_ua/">
                                    <span>Instagram</span>
                                </a>
                            </span>
                            <div class="boxFooterSocialLinksChildAltText">
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <nav class="themeMenuBottom mt-2">
        <ul class="themeMenuBottom-menu Disclaimer-text">

            <li class="themeMenuBottom__item themeMenuBottom__item--first" role="button">
                <a class="themeMenuBottom__link ">Про компанію</a>
            </li>


            <li class="themeMenuBottom__item" role="button">
                <a class="themeMenuBottom__link">Cookie Settings</a>
            </li>


            <li class="themeMenuBottom__item" role="button">
                <a class="themeMenuBottom__link">Конфіденційність персональних даних</a>
            </li>


            <li class="themeMenuBottom__item" role="button">
                <a class="themeMenuBottom__link">Умови користування</a>
            </li>


            <li class="themeMenuBottom__item" role="button">
                <a class="themeMenuBottom__link">Зворотний зв'язок</a>
            </li>


            <li class="themeMenuBottom__item themeMenuBottom__item--last" role="button">
                <a class="themeMenuBottom__link">Споживання пального</a>
            </li>

        </ul>
    </nav>

    <div class="Disclaimer">
        <h2>Дисклеймер від Volkswagen</h2>
        <div>
            <p>Наведені цифри були визначені у відповідності до методики вимірювання EG 715/2007 або EWG 80/1268. Ці цифри не стосуються певної конкретної моделі автомобіля і не становлять частину пропозиції, а наведені лише для порівняння різних типів автомобілів. На додаток до паливної економічності двигуна при визначенні витрат пального та викидів CO2 також мають значення манера керування, а також інші нетехнічні фактори, як, наприклад, умови навколишнього середовища. Окрім впливу погодних та автодорожніх умов додаткове обладнання та пристрої, розширений набір опцій, шини та інше можуть змінити важливі параметри автомобіля, такі як вага, опір руху та аеродинаміка, відповідно впливаючи на коефіцієнти витрати пального та характеристики управління. </p>
        </div>
    </div>

    <div class="Copyright">
        <p class="boxCopyright">
            <span>© ТОВ "VAG Dealer" 2023</span>
        </p>
    </div>

</footer>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Home page</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

</head>
<body>
    <header class="header">

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-transparent border-bottom-black box-shadow mb-3">
            <div class="container-fluid d-xl-flex justify-content-between">
                <div class="site-section d-xl-flex flex-xxl-row">
                    <a class="navbar-brand m-lg-3" asp-area="" asp-controller="Home" asp-action="Index">
                    <svg class="logo m-auto" xmlns="http://www.w3.org/2000/svg" asp-controller="Home" id="master-artboard" viewBox="0 0 1024 1024" version="1.1" x="0px" y="0px" style="enable-background:new 0 0 1400 980;" width="1024px" height="1024px">
                        <rect id="ee-background" x="0" y="0" width="1024" height="1024" style="fill: white; fill-opacity: 0; pointer-events: none;" />
                        <g transform="matrix(10.188387870788574, 0, 0, 10.188387870788574, -251.519936680809, -252.79260253906244)">
                            <switch>
                                <foreignObject requiredExtensions="&amp;ns_ai;" x="0" y="0" width="1" height="1">

                                </foreignObject>
                                <g>
                                    <path d="M -25 -25 H 175 V 175 H -25 V -25 Z" class="st0" style="fill: none;" />
                                    <path class="st1" d="M75,120.4c-24.9,0-45.3-20.5-45.3-45.4c0-5.6,1-10.9,2.9-15.9l26.5,53.3c0.3,0.7,0.8,1.3,1.6,1.3&#10;&#9;&#9;&#9;c0.8,0,1.3-0.6,1.6-1.3l12.2-27.3c0.1-0.3,0.3-0.6,0.6-0.6s0.4,0.3,0.6,0.6l12.2,27.3c0.3,0.7,0.8,1.3,1.6,1.3&#10;&#9;&#9;&#9;c0.8,0,1.3-0.6,1.6-1.3l26.5-53.3c1.9,5,2.9,10.3,2.9,15.9C120.3,99.9,99.9,120.4,75,120.4z M75,64.7c-0.3,0-0.4-0.3-0.6-0.6&#10;&#9;&#9;&#9;l-14.2-32c4.6-1.7,9.6-2.6,14.8-2.6c5.2,0,10.2,0.9,14.8,2.6l-14.2,32C75.4,64.5,75.3,64.7,75,64.7z M60.5,97.6&#10;&#9;&#9;&#9;c-0.3,0-0.4-0.3-0.6-0.6l-23-46.4c4.1-6.3,9.6-11.6,16.3-15.3l16.6,36.9C70,72.8,70.5,73,71,73h8c0.6,0,1-0.1,1.3-0.8l16.6-36.9&#10;&#9;&#9;&#9;c6.6,3.7,12.2,9,16.3,15.3L90,97c-0.1,0.3-0.3,0.6-0.6,0.6c-0.3,0-0.4-0.3-0.6-0.6l-8.7-19.8c-0.3-0.7-0.7-0.8-1.3-0.8h-8&#10;&#9;&#9;&#9;c-0.6,0-1,0.1-1.3,0.8L61.1,97C61,97.3,60.8,97.6,60.5,97.6z M75,125c27.7,0,50-22.3,50-50c0-27.7-22.3-50-50-50&#10;&#9;&#9;&#9;c-27.7,0-50,22.3-50,50C25,102.7,47.3,125,75,125z" style="fill: rgb(0, 30, 80);" />
                                </g>
                            </switch>
                        </g>
                    </svg>
                    VAG Dealer</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between align-items-center">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ModelList">Моделі</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="https://de.wikipedia.org/wiki/Volkswagen_AG">Історія Volkswagen AG</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="user-section navbar-collapse collapse d-xl-flex justify-content-end">
                    <ul class="navbar-nav me-xxl-5 d-xl-flex flex-xxl-column ">
                        <li class="nav-item dropdown">
                            <i class="fas fa-user nav-link user-icon" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
                            <div class="dropdown-menu dropdown-menu-relocate" aria-labelledby="navbarDropdownMenuLink">
                                <ul class="dropdown-container">
                                    <li class="dropdown-item @((bool)ViewBag.IsLoggedIn ? "logged-In" : "logged-Out")" role="button">
                                        <a class="text-black text-decoration-none d-xxl-flex" asp-area="" asp-controller="Home" asp-action="LogIn">
                                            <i class="fas fa-sign-in-alt"></i>
                                            <a class="text-black text-decoration-none" asp-area="" asp-controller="Home" asp-action="LogIn">Реєстрація/Вхід</a>
                                        </a>
                                    </li>
                                    <li class="dropdown-item @((bool)ViewBag.IsLoggedIn ? "logged-Out" : "logged-In")" role="button">
                                        <a class="text-black text-decoration-none d-xxl-flex" asp-area="" asp-controller="CreditCard" asp-action="CreditCard">
                                            <i class="far fa-credit-card"></i>
                                            <a class="text-black text-decoration-none" asp-area="" asp-controller="CreditCard" asp-action="CreditCard">Мої методи оплати</a>
                                        </a>
                                    </li>
                                    <li class="dropdown-item @((bool)ViewBag.IsLoggedIn ? "logged-Out" : "logged-In")" role="button">
                                        <a class="text-black text-decoration-none d-xxl-block" asp-area="" asp-controller="Home" asp-action="OrderList">
                                            <i class="fas fa-shopping-cart"></i>
                                            <a class="text-black text-decoration-none" asp-area="" asp-controller="Home" asp-action="OrderList">Мої покупки</a>
                                        </a>
                                    </li>
                                    <li class="dropdown-item @((bool)ViewBag.IsLoggedIn ? "logged-Out" : "logged-In")" role="button" >
                                        <a class="text-black text-decoration-none" asp-area="" asp-controller="Home" asp-action="LogOut">
                                            <i class="fas fa-sign-out-alt"></i>
                                            <a class="text-black text-decoration-none" asp-area="" asp-controller="Home" asp-action="LogOut">Вихід</a>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>