Models/LogInViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace KursovaWork.Models
{
    /// <summary>
    /// Клас для получення даних входу, які ввів користувач
    /// </summary>
    public class LogInViewModel
    {
        /// <summary>
        /// Електронна пошта
        /// </summary>
        [Required(ErrorMessage = "Поле Електронна пошта є потрібне.")]
        [EmailAddress(ErrorMessage = "Неправильна Електронна пошта.")]
        [Display(Name = "Електронна пошта")]
        public string Email { get; set; }

        /// <summary>
        /// Пароль
        /// </summary>
        [Required(ErrorMessage = "Поле паролю є потрібне.")]
        [DataType(DataType.Password)]
        [StringLength(100, MinimumLength = 6, ErrorMessage = "Пароль повинен містити мінімум 6 символів")]
        [Display(Name = "Пароль")]
        public string Password { get; set; }

    }

}

Controllers/ChangePasswordController.cs
using KursovaWorkDAL.Entity.Entities;
using KursovaWork.Models;
using KursovaWorkBLL.Services.AdditionalServices;
using KursovaWorkBLL.Services.MainServices.UserService;
using Microsoft.AspNetCore.Mvc;
using System.Text;

namespace KursovaWork.Controllers
{
    /// <summary>
    /// Контролер, що відповідає за зміну пароля користувача.
    /// </summary>
    public class ChangePasswordController : Controller
    {
        /// <summary>
        /// Сервіс для роботи з користувачем
        /// </summary>
        private readonly IUserService _userService;

        /// <summary>
        /// Об'єкт класу ILogger для логування подій 
        /// </summary>
        private readonly ILogger<ChangePasswordController> _logger;

        /// <summary>
        /// Об'єкт класу User? (nullable), який вказує на поточного користувача
        /// </summary>
        private static User? _curUser;

        /// <summary>
        /// Змінна, яка містить в собі поточний верифікаційний код
        /// </summary>
        private static int _verificationCode;

        /// <summary>
        /// Ініціалізує новий екземпляр класу <see cref="ChangePasswordController"/>.
        /// </summary>
        /// <param name="userService">Сервіс для роботи з користувачем.</param>
        /// <param name="logger">Логгер для запису логів.</param>
        public ChangePasswordController(IUserService userService, ILogger<ChangePasswordController> logger)
        {
            _userService = userService;
            _logger = logger;
        }

        /// <summary>
        /// Отримує сторінку для введення пошти користувача.
        /// </summary>
        /// <returns>Сторінка введення пошти користувача.</returns>
        public IActionResult UserFinder()
        {
            _logger.LogInformation("Перехід на сторінку введення пошти");
            return View("~/Views/ForgotPassword/UserFinder.cshtml");
        }

        /// <summary>
        /// Обробляє введену пошту користувача для відправки верифікаційного коду.
        /// </summary>
        /// <param name="model">Модель, що містить введену пошту користувача.</param>
        /// <returns>Сторінка введення верифікаційного коду або сторінка введення пошти з повідомленням про помилку.</returns>
        public IActionResult ForgotPassword(EmailViewModel model)
        {
            _logger.LogInformation("Вхід у метод верифікації електронної пошти");
            if(ModelState.IsValid)
            {
                _curUser = _userService.GetUserByEmail(model.Email);    
                if (_curUser != null)
                {
                    _logger.LogInformation("Пошту знайдено");
                    SendCode();
                    return Json(new { success = true });
                }
                _logger.LogInformation("Електронна пошта не є зареєстрованою");

                return Json(new {success = false, error = "Така електронна пошта не є зареєстрованою" });
            }

            string error = ModelState[nameof(EmailViewModel.Email)].Errors.FirstOrDefault()?.ErrorMessage ?? "";

            _logger.LogInformation("Дані не пройшли валідацію");
            return Json(new { success = false, error });
        }

        /// <summary>
        /// Обробляє введений верифікаційний код для переходу до сторінки зміни пароля користувача.
        /// </summary>
        /// <param name="model">Модель, що містить введений користувачем верифікаційний код.</param>
        /// <returns>Сторінка зміни пароля або сторінка введення верифікаційного коду з повідомленням про помилку.</returns>
        public IActionResult ChangePassword(VerificationViewModel model)
        {
            _logger.LogInformation("Вхід у метод верифікації коду");
            if (ModelState.IsValid)
            {
                StringBuilder stringBuilder = new StringBuilder();
                _logger.LogInformation("Переходимо в цикл утворення цілісного рядка з 4 підрядків");

                foreach (var digit in model.VerificationDigits)
                {
                    if (string.IsNullOrEmpty(digit))
                    {
                        _logger.LogInformation("Не введено всіх цифр");
                        return Json(new { success = false, error = "Не введено всіх цифр" });
                    }
                    stringBuilder.Append(digit);
                }

                string temp = stringBuilder.ToString();

                if (int.Parse(temp) != _verificationCode)
                {
                    _logger.LogInformation("Неправильний код підтвердження");

                    return Json(new { success = false, error = "Неправильний код підтвердження" });
                }

                _logger.LogInformation("Успішно підтверджено можливість для користувача на зміну паролю");

                return Json(new { success = true });
            }

            string error = ModelState[nameof(VerificationViewModel.VerificationDigits)].Errors.FirstOrDefault()?.ErrorMessage ?? "";

            _logger.LogInformation("Дані не пройшли валідацію");
            return Json(new { success = false, error });
        }

        /// <summary>
        /// Метод переходу на сторінку зміни паролю
        /// </summary>
        /// <returns>Сторінка зміни паролю</returns>
        public IActionResult UpdatePassword()
        {
            _logger.LogInformation("Перехід на сторінку зміни паролю");
            return View("~/Views/ForgotPassword/ChangePassword.cshtml");
        }

        /// <summary>
        /// Обробляє введений новий пароль користувача.
        /// </summary>
        /// <param name="model">Модель, що містить введений користувачем новий пароль.</param>
        /// <returns>Сторінка зміни пароля або сторінка введення нового пароля з повідомленням про помилку.</returns>
        [HttpPost]
        public IActionResult SubmitChange(ChangePasswordViewModel model)
        {
            _logger.LogInformation("Вхід у метод зміни паролю");
            if (ModelState.IsValid)
            {
                _logger.LogInformation("Дані пройшли валідацію");

                _userService.UpdatePasswordOfUser(model.Password, model.ConfirmPassword, _curUser);

                _logger.LogInformation("Успішно змінено пароль, переходимо на головну сторінку");

                return Json(new {success = true });

            }

            var errors = new
            {
                passwordError = ModelState[nameof(ChangePasswordViewModel.Password)].Errors.FirstOrDefault()?.ErrorMessage ?? "",
                confirmPasswordError = ModelState[nameof(ChangePasswordViewModel.ConfirmPassword)].Errors.FirstOrDefault()?.ErrorMessage ?? ""
            };

            _logger.LogInformation("Дані не пройшли валідацію");

            return Json(new {success = false, errors });
        }

        /// <summary>
        /// Відправляє електронний лист з верифікаційним кодом.
        /// </summary>
        /// <returns>Сторінка введення верифікаційного коду.</returns>
        public IActionResult SendVerificationCode()
        {
            _logger.LogInformation("Переходимо на сторінку з введенням коду");

            return View("~/Views/ForgotPassword/ForgotPassword.cshtml");
        }

        /// <summary>
        /// Відправляє заново електронний лист з новим верифікаційним кодом.
        /// </summary>
        /// <returns>Повідомлення про успішне надіслання коду</returns>
        public IActionResult ReSendVerificationCode()
        {
            SendCode();
            return Json(new { message = "Успішно надіслано код" });
        }

        /// <summary>
        /// Метод генерування коду та відправки листа
        /// </summary>
        public void SendCode()
        {
            _logger.LogInformation("Вхід у метод надсилання верифікаційного коду");

            _verificationCode = new Random().Next(1000, 9999);

            string subject = "Код підтвердження";

            string body = EmailBodyTemplate.BodyTemp(_curUser.FirstName, _curUser.LastName, _verificationCode, "зміни паролю");

            _logger.LogInformation("Надсилаємо повідомлення на електронну пошту користувача");

            EmailSender.SendEmail(_curUser.Email, subject, body);
        }
    }
}

Controllers/LogInController.cs
using KursovaWork.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using KursovaWorkBLL.Services.MainServices.UserService;

namespace KursovaWork.Controllers
{
    /// <summary>
    /// Контролер, що відповідає за вхід користувача в обліковий запис.
    /// </summary>
    public class LogInController : Controller
    {
        /// <summary>
        /// Сервіс для роботи з користувачами
        /// </summary>
        private readonly IUserService _userService;

        /// <summary>
        /// Об'єкт класу ILogger для логування подій 
        /// </summary>
        private readonly ILogger<LogInController> _logger;

        /// <summary>
        /// Ініціалізує новий екземпляр класу <see cref="LogInController"/>.
        /// </summary>
        /// <param name="userService">Сервіс для роботи з користувачами.</param>
        /// <param name="logger">Логгер для запису логів.</param>
        public LogInController(IUserService userService, ILogger<LogInController> logger)
        {
            _userService = userService;
            _logger = logger;
        }

        /// <summary>
        /// Отримує сторінку входу.
        /// </summary>
        /// <returns>Сторінка входу.</returns>
        public IActionResult LogIn()
        {
            _logger.LogInformation("Перехід на сторінку входу");
            return View();
        }

        /// <summary>
        /// Отримує сторінку реєстрації.
        /// </summary>
        /// <returns>Сторінка реєстрації.</returns>
        public IActionResult SignUp()
        {
            _logger.LogInformation("Перехід на сторінку реєстрації");
            return View("~/Views/SignUp/SignUp.cshtml");
        }

        /// <summary>
        /// Обробляє введені користувачем дані входу та аутентифікує користувача.
        /// </summary>
        /// <param name="model">Модель, що містить введені користувачем дані входу.</param>
        /// <returns>Сторінка головного меню або сторінка входу з повідомленням про помилку.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult LogIn(LogInViewModel model)
        {
            _logger.LogInformation("Вхід у метод перевірки даних входу");
            if (ModelState.IsValid)
            {
                var user = _userService.ValidateUser(model.Email, model.Password);

                if (user != null)
                {

                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, user.Email),
                        new Claim(ClaimTypes.NameIdentifier, user.Id.ToString())
                    };

                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    var principal = new ClaimsPrincipal(identity);

                    var authProperties = new AuthenticationProperties
                    {
                        IsPersistent = true
                    };

                    HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal, authProperties).Wait();

                    _logger.LogInformation("Користувач успішно ввійшов в обліковий запис");

                    return Json(new { success = true });
                }

                _logger.LogInformation("Електронну пошту або пароль введено неправильно");
                var error = "Неправильна електронна пошта або пароль.";

                return Json(new { success = false, error  });

            }

            var errors = new
            {
                emailError = ModelState[nameof(LogInViewModel.Email)].Errors.FirstOrDefault()?.ErrorMessage ?? "",
                passwordError = ModelState[nameof(LogInViewModel.Password)].Errors.FirstOrDefault()?.ErrorMessage ?? "",
            };

            _logger.LogInformation("Дані не пройшли валідацію");
            return Json(new { success = false, errors });
        }

    }


}

Views/LogIn/LogIn.cshtml
@using KursovaWorkBLL.Services.AdditionalServices;
@{
    ViewBag.Title = "LogIn";
    ViewBagHelper.SetIsLoggedInInViewBag(ViewContext);
}
@model LogInViewModel

<script>
    var element = document.querySelector('.header');
    element.remove();
</script>
<div class="splitted-page">
    <div class="left-side">
        <div class="input-group">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 offset-md-3">
                        <div class="d-flex justify-content-center align-items-center mb-3">
                            <a class="m-lg-3" asp-area="" asp-controller="Home" asp-action="Index">
                                <svg class="logo-login m-auto" xmlns="http://www.w3.org/2000/svg" asp-controller="Home" id="master-artboard" viewBox="0 0 1024 1024" version="1.1" x="0px" y="0px" style="enable-background: new 0 0 1400 980;" width="1024px" height="1024px">
                                    <rect id="ee-background" x="0" y="0" width="1024" height="1024" style="fill: white; fill-opacity: 0; pointer-events: none;" />
                                    <g transform="matrix(10.188387870788574, 0, 0, 10.188387870788574, -251.519936680809, -252.79260253906244)">
                                        <switch>
                                            <foreignObject requiredExtensions="&amp;ns_ai;" x="0" y="0" width="1" height="1">

                                            </foreignObject>
                                            <g>
                                                <path d="M -25 -25 H 175 V 175 H -25 V -25 Z" class="st0" style="fill: none;" />
                                                <path class="st1" d="M75,120.4c-24.9,0-45.3-20.5-45.3-45.4c0-5.6,1-10.9,2.9-15.9l26.5,53.3c0.3,0.7,0.8,1.3,1.6,1.3&#10;&#9;&#9;&#9;c0.8,0,1.3-0.6,1.6-1.3l12.2-27.3c0.1-0.3,0.3-0.6,0.6-0.6s0.4,0.3,0.6,0.6l12.2,27.3c0.3,0.7,0.8,1.3,1.6,1.3&#10;&#9;&#9;&#9;c0.8,0,1.3-0.6,1.6-1.3l26.5-53.3c1.9,5,2.9,10.3,2.9,15.9C120.3,99.9,99.9,120.4,75,120.4z M75,64.7c-0.3,0-0.4-0.3-0.6-0.6&#10;&#9;&#9;&#9;l-14.2-32c4.6-1.7,9.6-2.6,14.8-2.6c5.2,0,10.2,0.9,14.8,2.6l-14.2,32C75.4,64.5,75.3,64.7,75,64.7z M60.5,97.6&#10;&#9;&#9;&#9;c-0.3,0-0.4-0.3-0.6-0.6l-23-46.4c4.1-6.3,9.6-11.6,16.3-15.3l16.6,36.9C70,72.8,70.5,73,71,73h8c0.6,0,1-0.1,1.3-0.8l16.6-36.9&#10;&#9;&#9;&#9;c6.6,3.7,12.2,9,16.3,15.3L90,97c-0.1,0.3-0.3,0.6-0.6,0.6c-0.3,0-0.4-0.3-0.6-0.6l-8.7-19.8c-0.3-0.7-0.7-0.8-1.3-0.8h-8&#10;&#9;&#9;&#9;c-0.6,0-1,0.1-1.3,0.8L61.1,97C61,97.3,60.8,97.6,60.5,97.6z M75,125c27.7,0,50-22.3,50-50c0-27.7-22.3-50-50-50&#10;&#9;&#9;&#9;c-27.7,0-50,22.3-50,50C25,102.7,47.3,125,75,125z" style="fill: rgb(0, 30, 80);" />
                                            </g>
                                        </switch>
                                    </g>
                                </svg>
                            </a>
                        </div>
                        <h2 class="text-center mb-4">VAG ID Login</h2>
                        <div class="customLogInHeader fs-5">
                            <p>
                                Ви ще немаєте VAG ID? Нажміть
                                <a class="text-black" asp-area="" asp-controller="LogIn" asp-action="SignUp">тут</a>
                            </p>
                        </div>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        @using (Html.BeginForm("LogIn", "LogIn", FormMethod.Post, new { @class = "needs-validation", @id = "loginForm", novalidate = "novalidate" }))
                        {
                            <div class="form-group">
                                <p class="emailP fs-6">VAG ID (Електронна пошта)</p>
                                @Html.TextBoxFor(m => m.Email, new { @class = "form-control-custom", placeholder = "Електронна пошта", required = "required", autofocus = "autofocus" })
                                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger", @id = "emailError" })
                            </div>

                            <div class="form-group">
                                <p class="passwordP fs-6">Пароль</p>
                                @Html.PasswordFor(m => m.Password, new { @class = "form-control-custom", placeholder = "Пароль", required = "required" })
                                @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger", @id = "passwordError" })
                            </div>


                            <div class="form-group login-button">
                                <button type="submit" class="btn btn-primary btn-block">Ввійти</button>
                            </div>

                        }
                        <div class="customLogInHeader fs-5">
                            <p>
                                Забули пароль, нажміть
                                <a asp-action="UserFinder" asp-controller="ChangePassword">тут</a>
                            </p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="right-side"></div>
    <div class="right-side-mobile"></div>
</div>
<script>
    document.addEventListener("DOMContentLoaded",
        function () {
            document.getElementById("loginForm").addEventListener("submit",
                function (event) {
                    event.preventDefault();
                    logIn();
                });
        });

    function logIn() {
        var form = document.getElementById("loginForm");
        var formData = new FormData(form);

        fetch(form.action,
            {
                method: form.method,
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    window.location.href = "@Url.Action("Index", "Home")";
                } else {
                    if (data.errors) {
                        if (data.errors.emailError) {
                            document.getElementById("emailError").innerText = data.errors.emailError;
                        } else {
                            document.getElementById("emailError").innerText = "";
                        }

                        if (data.errors.passwordError) {
                            document.getElementById("passwordError").innerText = data.errors.passwordError;
                        } else {
                            document.getElementById("passwordError").innerText = "";
                        }
                    }else if (data.error) {
                        document.getElementById("passwordError").innerText = data.error;
                    }
                }
            })
            .catch(error => console.log(error));
    }

</script>