Controllers/ConfiguratorController.cs
using KursovaWorkDAL.Entity.Entities.Car;
using Microsoft.AspNetCore.Mvc;
using KursovaWorkDAL.Entity.Entities;
using KursovaWorkBLL.Services.MainServices.CarService;

namespace KursovaWork.Controllers
{
    /// <summary>
    /// Контролер, що відповідає за обробку дій пов'язаних з конфігурацією автомобіля.
    /// </summary>
    public class ConfiguratorController : Controller
    {
        /// <summary>
        /// Сервіс для роботи з автомобілями
        /// </summary>
        private readonly ICarService _carService;

        /// <summary>
        /// Об'єкт класу ILogger для логування подій 
        /// </summary>
        private readonly ILogger<ConfiguratorController> _logger;

        /// <summary>
        /// Об'єкт класу CarInfo? (nullable), який вказує на поточну машину
        /// </summary>
        private static CarInfo _curCar;

        /// <summary>
        /// Об'єкт класу ConfiguratorOptions? (nullable), який вказує на обрані опції в конфігураторі
        /// </summary>
        public static ConfiguratorOptions? options { get; set; }

        /// <summary>
        /// Масив рядків, в якому знаходяться: Марка машини - індекс 0, Модель машини - індекс 1, Рік виробництва - індекс 2
        /// </summary>
        private static string[] _param = new string[3];

        /// <summary>
        /// Ініціалізує новий екземпляр класу <see cref="ConfiguratorController"/>.
        /// </summary>
        /// <param name="carService">Сервіс для роботи з автомобілями.</param>
        /// <param name="logger">Логгер для запису логів.</param>
        public ConfiguratorController(ICarService carService, ILogger<ConfiguratorController> logger)
        {
            _carService = carService;
            _logger = logger;
        }

        /// <summary>
        /// Отримує сторінку з конфігуратором автомобіля.
        /// </summary>
        /// <param name="param1">Параметр 1 (марка автомобіля).</param>
        /// <param name="param2">Параметр 2 (модель автомобіля).</param>
        /// <param name="param3">Параметр 3 (рік виробництва автомобіля).</param>
        /// <returns>Сторінка з конфігуратором автомобіля або сторінка помилки.</returns>
        public IActionResult Configurator(string param1, string param2, string param3)
        {
            _logger.LogInformation("Вхід у функцію переходу на конфігуратор");

            _param = new[] { param1, param2, param3 };

            int year = int.Parse(param3);

            CarInfo car = _carService.GetCarByInfo(param1, param2, year);

            _curCar = car;

            _logger.LogInformation("Машину знайдено, перехід на сторінку конфігуратора");
            return View(car);
        }

        /// <summary>
        /// Обробляє вибрані параметри конфігурації автомобіля.
        /// </summary>
        /// <param name="color">Колір автомобіля.</param>
        /// <param name="transmission">Тип коробки передач автомобіля.</param>
        /// <param name="fuelType">Тип палива автомобіля.</param>
        /// <returns>Сторінка оплати автомобіля або сторінка конфігуратора з повідомленнями про помилки.</returns>
        public IActionResult Submit(string color, string transmission, string fuelType)
        {
            _logger.LogInformation("Вхід у функцію підтвердження конфігурації автомобіля");

            var errors = new Dictionary<string, string>();

            if (string.IsNullOrEmpty(color))
            {
                errors["color"] = "Виберіть колір";
                _logger.LogInformation("Колір не було обрано");
            }

            if (string.IsNullOrEmpty(transmission))
            {
                errors["transmission"] = "Виберіть тип коробки передач";
                _logger.LogInformation("Тип коробки передач не було обрано");
            }

            if (string.IsNullOrEmpty(fuelType))
            {
                errors["fuelType"] = "Виберіть тип палива";
                _logger.LogInformation("Тип палива не було обрано");
            }

            if (errors.Count > 0)
            {
                _logger.LogInformation("Один або більше параметрів не було обрано в конфігураторі");
                return Json(new { errors });
            }

            options = new ConfiguratorOptions()
            {
                Color = color,
                Transmission = transmission,
                FuelType = fuelType
            };

            _logger.LogInformation("Перехід на сторінку оплати автомобіля");
            return Json(new { redirect = Url.Action("Payment", "Payment", new { param1 = _param[0], param2 = _param[1], param3 = _param[2] }) });
        }
    }
}

Views/Configurator/Configurator.cshtml
@using KursovaWorkDAL.Entity.Entities.Car;
@using KursovaWorkBLL.Services.AdditionalServices;

@model CarInfo;
@{
    ViewBag.Title = Model.Make + " " + Model.Model + " - Конфігуратор";
    ViewBagHelper.SetIsLoggedInInViewBag(ViewContext);
}

<h2 class="mb-2">@Model.Make @Model.Model</h2>

<div class="homepage-mainsection">
    <div class="main-carousel autoplay">
        @foreach(var image in Model.Images)
        {
            <div class="carousel-cell">
                <img src="@image.ImageUrl"/>
            </div>
        }

    </div>
</div>

<div class="carBody d-flex flex-column">
    <form asp-action="Submit" asp-controller="Configurator" method="post" id="configuratorForm">
        <div class="form-group">
            <h4>Колір</h4>
            <div class="radio-buttons flex-row justify-content-between">
                <label class="cursor">
                    <input type="radio" name="color" value="Червоний">
                    <span class="radio-button bg-red"></span>
                    Червоний
                </label>
                <label class="cursor">
                    <input type="radio" name="color" value="Синій">
                    <span class="radio-button bg-blue"></span>
                    Синій
                </label>
                <label class="cursor">
                    <input type="radio" name="color" value="Чорний">
                    <span class="radio-button bg-black"></span>
                    Чорний
                </label>
                <label class="cursor">
                    <input type="radio" name="color" value="Білий">
                    <span class="radio-button bg-light"></span>
                    Білий
                </label>
                <label class="cursor">
                    <input type="radio" name="color" value="Сріблястий">
                    <span class="radio-button bg-silver"></span>
                    Сріблястий
                </label>
            </div>
            <p id="colorError" class="text-danger"></p>
            
        </div>

        <div class="form-group">
            <h4>Тип коробки передач</h4>
            <div class="radio-buttons">
                <label class="cursor">
                    <input type="radio" name="transmission" value="Механічна">
                    <span class="radio-button"></span>
                    Механічна
                </label>
                <label class="cursor">
                    <input type="radio" name="transmission" value="Автоматична">
                    <span class="radio-button"></span>
                    Автоматична
                </label>
                <label class="cursor">
                    <input type="radio" name="transmission" value="Роботична">
                    <span class="radio-button"></span>
                    Роботична
                </label>
            </div>
            <p id="transmissionError" class="text-danger"></p>
            
        </div>

        <div class="form-group">
            <h4>Тип палива</h4>
            <div class="radio-buttons">
                <label class="cursor">
                    <input type="radio" name="fuelType" value="Бензин">
                    <span class="radio-button"></span>
                    Бензин
                </label>
                <label class="cursor">
                    <input type="radio" name="fuelType" value="Дизель">
                    <span class="radio-button"></span>
                    Дизель
                </label>
                <label>
                    <input type="radio" name="fuelType" value="Електричний">
                    <span class="radio-button"></span>
                    Електричний
                </label>
                <label class="cursor">
                    <input type="radio" name="fuelType" value="Гибрид">
                    <span class="radio-button"></span>
                    Гибрид
                </label>
            </div>
            <p id="fuelTypeError" class="text-danger"></p>
            
        </div>

        <button id="submitButton" type="submit" class="btn btn-primary">Зберегти</button>
    </form>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        document.getElementById("configuratorForm").addEventListener("submit", function (event) {
            event.preventDefault();
            submitConfiguratorForm();
        });
    });

    function submitConfiguratorForm() {
        var form = document.getElementById("configuratorForm");
        var formData = new FormData(form);

        fetch(form.action, {
                method: form.method,
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                if (data.redirect) {
                    window.location.href = data.redirect;
                } else {
                    if (data.errors) {
                        if (data.errors.color) {
                            document.getElementById("colorError").innerHTML = data.errors.color;
                        } else {
                            document.getElementById("colorError").innerHTML = "";
                        }

                        if (data.errors.transmission) {
                            document.getElementById("transmissionError").innerHTML = data.errors.transmission;
                        } else {
                            document.getElementById("transmissionError").innerHTML = "";
                        }

                        if (data.errors.fuelType) {
                            document.getElementById("fuelTypeError").innerHTML = data.errors.fuelType;
                        } else {
                            document.getElementById("fuelTypeError").innerHTML = "";
                        }
                    }
                }
            })
            .catch(error => console.log(error));
    }

</script>

@Html.Partial("_Footer")